name: Build UI Kit and Deploy Storybook

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build UI Kit
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Исправлено с v3 на v4
        with:
          name: build-artifacts
          path: dist/

  deploy-storybook:
    name: Deploy Storybook
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Также обновлено до v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./storybook-static