name: Publish UI Kit to NPM

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install and build
        run: |
          npm ci
          npm run build
          ls -R dist # Проверка собранных файлов

      - name: Get package info
        id: package
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          CURRENT_VERSION=$(npm view ${{ steps.package.outputs.PACKAGE_NAME }} version 2>/dev/null || echo "0.0.0")
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          case "${{ inputs.version_type }}" in
            major) major=$((major + 1)); minor=0; patch=0;;
            minor) minor=$((minor + 1)); patch=0;;
            patch) patch=$((patch + 1));;
          esac
          NEW_VERSION="${major}.${minor}.${patch}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          npm version $NEW_VERSION --no-git-tag-version

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm publish --access public
          echo "Published ${{ steps.package.outputs.PACKAGE_NAME }}@${{ steps.bump.outputs.NEW_VERSION }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump.outputs.NEW_VERSION }}
          release_name: v${{ steps.bump.outputs.NEW_VERSION }}
          body: |
            ## Changes in v${{ steps.bump.outputs.NEW_VERSION }}
            - Version bump: ${{ inputs.version_type }}
          draft: false
          prerelease: false