name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major
      custom_version:
        description: 'OR exact version (e.g. 1.2.3)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Versioning
        run: |
          if [ -n "${{ inputs.custom_version }}" ]; then
            standard-version --release-as ${{ inputs.custom_version }}
          else
            npm run version:${{ inputs.version_type }}
          fi

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
          git push --follow-tags origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true